# -*- coding: utf-8 -*-

{
    'name': 'Property Administration',
    'category': 'General',
    'summary': 'Property Administration',
    'description': 'Property Administration',
    'depends': [
        'property_management', 'account'
    ],
    'data': ['views/cost_type.xml',
             'views/tenancy.xml',
             'views/rent.xml',
             'views/expenditure.xml',
             'views/journal.xml',
             'views/managed_objects.xml',
             'views/account_view.xml',
             # 'views/product_view.xml',
             'views/property_view.xml',
             'views/res_users_view.xml',
             'views/portal_template.xml',
             'views/res_config_setting_view.xml',
             'views/res_partner_view.xml',
             'views/businessplan_expenditure.xml',
             'views/businessplan_journal.xml',
             'views/businessplan.xml',
             'security/ir.model.access.csv',
             'security/security.xml',
             'wizard/split_cost.xml',
             'wizard/utility_bill.xml',
             'wizard/expenditure.xml',
             'wizard/landlord_certificate.xml',
             'wizard/split_cost_business.xml',
             'wizard/utility_bill_business.xml',
             'data/ir_cron.xml',
             'reports/landlord_certificate_report.xml',
             'reports/tenancy_contract_report.xml',
             'reports/miete_view.xml',
             'reports/betriebskostenabrechnung_view.xml',
             'reports/weg_abrechnung.xml'
             ],
    'demo': ['demo/demo.xml'],
    'assets': {
        'web.assets_frontend': [
            'property_administration/static/src/scss/document_layout.scss',
        ],
    },
    'installable': True,
    'application': False,
}
